// scripts/build-huc8.mjs
//
// One-shot build for the Watersheds (HUC8) layer on /sandbox/us-map.
// Pulls ~2,200 HUC8 (Subbasin) polygons from the USGS National Map's
// Watershed Boundary Dataset MapServer at moderate simplification
// (~2 km tolerance, 3-decimal precision) so the resulting GeoJSON
// stays under 2 MB.
//
// Source: https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/4
// HUC8 codes are 8 digits where the first 2 are the parent HUC2
// region (Mississippi, Missouri, Pacific NW, etc.) — we use that
// prefix to color watersheds by region.
//
// Run with:  node scripts/build-huc8.mjs

import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const OUT_DIR = resolve(REPO_ROOT, 'functions/sandbox/data');

const ENDPOINT = 'https://hydro.nationalmap.gov/arcgis/rest/services/wbd/MapServer/4/query';
const PAGE_SIZE = 1000;  // server max is 2000 but smaller pages are more reliable
const FIELDS = 'huc8,name,states';

// Drop watersheds whose `states` field only contains territories — those
// don't render on AlbersUSA anyway and just bloat the file.
function isInLower48OrAKHI(states) {
  if (!states) return true;  // keep on doubt
  // states is a comma-separated USPS list, e.g. "MI" or "TX,LA"
  var arr = states.split(',').map(s => s.trim());
  return arr.some(s => !['PR','VI','GU','MP','AS'].includes(s));
}

async function fetchPage(offset) {
  var qs = new URLSearchParams({
    where: '1=1',
    outFields: FIELDS,
    returnGeometry: 'true',
    outSR: '4326',
    geometryPrecision: '3',
    maxAllowableOffset: '0.02',
    orderByFields: 'huc8',
    resultOffset: String(offset),
    resultRecordCount: String(PAGE_SIZE),
    f: 'geojson',
  });
  const url = ENDPOINT + '?' + qs;
  const res = await fetch(url, { headers: { 'user-agent': 'c-lars-pms-sandbox-builder/1.0' } });
  if (!res.ok) throw new Error('HUC8 fetch failed at offset ' + offset + ': ' + res.status);
  return res.json();
}

async function main() {
  const features = [];
  let offset = 0;
  for (;;) {
    process.stdout.write(`fetching offset ${offset}... `);
    const page = await fetchPage(offset);
    if (!page.features || page.features.length === 0) break;
    page.features.forEach(f => {
      if (!isInLower48OrAKHI(f.properties.states)) return;
      features.push({
        type: 'Feature',
        properties: {
          huc8: f.properties.huc8,
          name: f.properties.name,
          states: f.properties.states,
        },
        geometry: f.geometry,
      });
    });
    console.log('cumulative ' + features.length);
    if (page.features.length < PAGE_SIZE) break;
    offset += PAGE_SIZE;
  }
  console.log(`final feature count: ${features.length}`);

  // Sort by huc8 (alphabetical = HUC2 region order). Renderer can
  // then count regions easily.
  features.sort((a, b) => a.properties.huc8.localeCompare(b.properties.huc8));

  const fc = { type: 'FeatureCollection', features };
  const json = JSON.stringify(fc);
  console.log(`payload size: ${(json.length / 1024).toFixed(0)} KB`);

  await mkdir(OUT_DIR, { recursive: true });
  const jsPath = resolve(OUT_DIR, 'huc8_geometry.js');
  await writeFile(jsPath, `// Auto-generated by scripts/build-huc8.mjs.
// DO NOT EDIT — re-run the script to refresh.
// HUC8 (Subbasin) watershed polygons, ~${Math.round(features.length / 100) * 100}
// features. Properties: { huc8, name, states }. The first 2 digits of
// huc8 give the parent HUC2 region (used for categorical coloring).
// Source: USGS National Map WBD MapServer.

export const HUC8_GEOJSON = ${json};
`);
  console.log(`wrote ${jsPath}`);
}

main().catch(err => { console.error(err); process.exit(1); });
