// scripts/build-msa.mjs
//
// One-shot build for MSA layers on /sandbox/us-map. Combines:
//   1. CBSA cartographic boundaries at 1:20m (loganpowell mirror of
//      Census 2017 generalized shapefile) — both Metropolitan and
//      Micropolitan Statistical Areas, ~945 features.
//   2. ACS 5-year 2022 estimates per CBSA:
//        B19013_001E — median household income
//        B25077_001E — median home value
//
// Writes:
//   functions/sandbox/data/cbsa_geometry.js     (~800 KB)
//   functions/sandbox/data/cbsa_income.js       (~10 KB)
//   functions/sandbox/data/cbsa_home_value.js   (~10 KB)
//
// Run with:  node scripts/build-msa.mjs

import { writeFile, readFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const DATA_DIR  = resolve(REPO_ROOT, 'functions/sandbox/data');

const TMP = tmpdir();
const GEO_URL  = 'https://raw.githubusercontent.com/loganpowell/census-geojson/master/GeoJSON/20m/2017/metropolitan-statistical-area%21micropolitan-statistical-area.json';
const ACS_URL  = 'https://api.census.gov/data/2022/acs/acs5?get=NAME,B19013_001E,B25077_001E&for=metropolitan%20statistical%20area/micropolitan%20statistical%20area:*';

async function fetchCached(url, name) {
  const cache = join(TMP, name);
  if (existsSync(cache)) {
    const txt = await readFile(cache, 'utf8');
    if (txt.length > 1000) return txt;
  }
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${name} fetch ${res.status}`);
  const txt = await res.text();
  await writeFile(cache, txt);
  return txt;
}

async function main() {
  console.log('Downloading CBSA GeoJSON...');
  const geoTxt = await fetchCached(GEO_URL, 'cbsa.geojson');
  const geo = JSON.parse(geoTxt);
  console.log(`  ${geo.features.length} CBSA features`);

  // Strip extra properties so the geojson is small. Keep just GEOID,
  // NAME, LSAD (M1=Metro, M2=Micro). Round coords to 4 decimals
  // (~11m precision at 40°N) to shrink the file ~30%.
  function roundCoord(n) { return Math.round(n * 10000) / 10000; }
  function roundGeom(g) {
    if (!g || !g.coordinates) return g;
    const round = function r(arr) {
      if (typeof arr[0] === 'number') return [roundCoord(arr[0]), roundCoord(arr[1])];
      return arr.map(r);
    };
    return { type: g.type, coordinates: round(g.coordinates) };
  }
  const slim = {
    type: 'FeatureCollection',
    features: geo.features.map(f => ({
      type: 'Feature',
      properties: {
        geoid: f.properties.GEOID,
        name: f.properties.NAME,
        lsad: f.properties.LSAD,  // M1=Metro, M2=Micro
      },
      geometry: roundGeom(f.geometry),
    })),
  };

  const geoJsPath = resolve(DATA_DIR, 'cbsa_geometry.js');
  await mkdir(DATA_DIR, { recursive: true });
  await writeFile(geoJsPath, `// Auto-generated by scripts/build-msa.mjs.
// DO NOT EDIT — re-run the script to refresh.
// US Core-Based Statistical Areas (Metropolitan + Micropolitan).
// Properties: { geoid, name, lsad } where lsad is "M1" (Metro) or "M2" (Micro).
// Source: ${GEO_URL}

export const CBSA_GEOJSON = ${JSON.stringify(slim)};
`);
  console.log(`  wrote ${geoJsPath} (${(JSON.stringify(slim).length / 1024).toFixed(0)} KB)`);

  // ACS data --------------------------------------------------------
  console.log('Downloading ACS API...');
  const acsTxt = await fetchCached(ACS_URL, 'acs-msa.json');
  const acs = JSON.parse(acsTxt);
  const header = acs[0];
  const iName = header.indexOf('NAME');
  const iIncome = header.indexOf('B19013_001E');
  const iHome = header.indexOf('B25077_001E');
  const iCbsa = header.indexOf('metropolitan statistical area/micropolitan statistical area');

  const income = {}, homeValue = {};
  for (let i = 1; i < acs.length; i++) {
    const r = acs[i];
    const cbsa = String(r[iCbsa]);
    const inc = parseInt(r[iIncome], 10);
    const home = parseInt(r[iHome], 10);
    if (Number.isFinite(inc) && inc > 0) income[cbsa] = inc;
    if (Number.isFinite(home) && home > 0) homeValue[cbsa] = home;
  }
  console.log(`  income coverage: ${Object.keys(income).length}, home value: ${Object.keys(homeValue).length}`);

  const incJsPath = resolve(DATA_DIR, 'cbsa_income.js');
  await writeFile(incJsPath, `// Auto-generated by scripts/build-msa.mjs.
// Median household income (USD) per CBSA. ACS 2022 5-year B19013.

export const CBSA_INCOME = ${JSON.stringify(income)};
`);
  console.log(`  wrote ${incJsPath}`);

  const homeJsPath = resolve(DATA_DIR, 'cbsa_home_value.js');
  await writeFile(homeJsPath, `// Auto-generated by scripts/build-msa.mjs.
// Median owner-occupied home value (USD) per CBSA. ACS 2022 5-year B25077.

export const CBSA_HOME_VALUE = ${JSON.stringify(homeValue)};
`);
  console.log(`  wrote ${homeJsPath}`);
}

main().catch(err => { console.error(err); process.exit(1); });
