// scripts/build-zcta.mjs
//
// One-shot build for ZCTA layers on /sandbox/us-map. Pulls ~33K ZIP
// code tabulation areas from the Census TIGERweb MapServer at
// aggressive simplification (~5km tolerance, 3-decimal precision)
// so the resulting GeoJSON lands at ~8 MB instead of 200+ MB.
//
// Source: https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/PUMA_TAD_TAZ_UGA_ZCTA/MapServer/1
//   (Layer 1 = 2020 ZCTAs)
//
// Also pulls ACS 5-year 2022 estimates per ZCTA:
//   B19013_001E — median household income
//   B01003_001E — total population (used for population layer)
//
// Run with:  node scripts/build-zcta.mjs

import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, '..');
const OUT_DIR = resolve(REPO_ROOT, 'functions/sandbox/data');

const TIGER_URL = 'https://tigerweb.geo.census.gov/arcgis/rest/services/TIGERweb/PUMA_TAD_TAZ_UGA_ZCTA/MapServer/1/query';
const ACS_URL = 'https://api.census.gov/data/2022/acs/acs5?get=NAME,B19013_001E,B01003_001E&for=zip%20code%20tabulation%20area:*';

const PAGE_SIZE = 1000;
const TOLERANCE = 0.05;        // ~5 km — fine for national-scale chloropleth
const COORD_PRECISION = 3;     // 3 decimal places ≈ 110 m

async function fetchPage(offset) {
  const qs = new URLSearchParams({
    where: '1=1',
    outFields: 'GEOID',
    returnGeometry: 'true',
    outSR: '4326',
    geometryPrecision: String(COORD_PRECISION),
    maxAllowableOffset: String(TOLERANCE),
    orderByFields: 'GEOID',
    resultOffset: String(offset),
    resultRecordCount: String(PAGE_SIZE),
    f: 'geojson',
  });
  const url = TIGER_URL + '?' + qs;
  const res = await fetch(url, { headers: { 'user-agent': 'c-lars-pms-sandbox/1.0' } });
  if (!res.ok) throw new Error('ZCTA fetch ' + res.status);
  return res.json();
}

async function fetchACS() {
  console.log('ACS:', ACS_URL);
  const res = await fetch(ACS_URL);
  if (!res.ok) throw new Error('ACS fetch ' + res.status);
  return res.json();
}

// Drop ZIPs in territories that AlbersUSA won't render anyway.
// PR ZIPs start with 006/007/009; USVI 008; GU/MP/AS in 96910-96952/96799/etc.
function isInLower48OrAKHI(geoid) {
  const prefix3 = geoid.slice(0, 3);
  if (['006','007','008','009'].includes(prefix3)) return false;  // PR/VI
  if (geoid >= '96799' && geoid <= '96799') return false;          // AS
  if (geoid >= '96910' && geoid <= '96932') return false;          // GU
  if (geoid >= '96950' && geoid <= '96952') return false;          // MP
  return true;
}

async function main() {
  const features = [];
  let offset = 0;
  for (;;) {
    process.stdout.write(`offset ${offset}... `);
    const page = await fetchPage(offset);
    const got = page.features?.length || 0;
    if (got === 0) break;
    let kept = 0;
    for (const f of page.features) {
      const geoid = f.properties?.GEOID;
      if (!geoid) continue;
      if (!isInLower48OrAKHI(geoid)) continue;
      features.push({
        type: 'Feature',
        properties: { z: geoid },  // shorter key to save bytes ×33K
        geometry: f.geometry,
      });
      kept++;
    }
    console.log(`page kept ${kept}, total ${features.length}`);
    if (got < PAGE_SIZE) break;
    offset += PAGE_SIZE;
  }
  console.log(`final ZCTA features: ${features.length}`);

  features.sort((a, b) => a.properties.z.localeCompare(b.properties.z));

  const fc = { type: 'FeatureCollection', features };
  const geomJson = JSON.stringify(fc);
  console.log(`geometry payload: ${(geomJson.length / 1024 / 1024).toFixed(1)} MB`);

  await mkdir(OUT_DIR, { recursive: true });
  const geomJsPath = resolve(OUT_DIR, 'zcta_geometry.js');
  await writeFile(geomJsPath, `// Auto-generated by scripts/build-zcta.mjs.
// DO NOT EDIT — re-run the script to refresh.
// 2020 Census ZIP Code Tabulation Areas (~33K), simplified to
// ~${Math.round(TOLERANCE * 111)}km tolerance for national-scale rendering.
// Properties: { z: 5-digit ZCTA code }.
// Source: TIGERweb MapServer (PUMA_TAD_TAZ_UGA_ZCTA layer 1).

export const ZCTA_GEOJSON = ${geomJson};
`);
  console.log(`wrote ${geomJsPath}`);

  // ACS data per ZCTA
  console.log('Fetching ACS...');
  const acs = await fetchACS();
  const header = acs[0];
  const iIncome = header.indexOf('B19013_001E');
  const iPop = header.indexOf('B01003_001E');
  const iZcta = header.indexOf('zip code tabulation area');

  const income = {}, pop = {};
  for (let i = 1; i < acs.length; i++) {
    const r = acs[i];
    const z = String(r[iZcta]);
    const inc = parseInt(r[iIncome], 10);
    const p = parseInt(r[iPop], 10);
    if (Number.isFinite(inc) && inc > 0) income[z] = inc;
    if (Number.isFinite(p) && p > 0) pop[z] = p;
  }
  console.log(`income: ${Object.keys(income).length}, pop: ${Object.keys(pop).length}`);

  await writeFile(resolve(OUT_DIR, 'zcta_income.js'),
`// Auto-generated. Median household income per ZCTA, ACS 2022 5-year B19013.
export const ZCTA_INCOME = ${JSON.stringify(income)};
`);
  await writeFile(resolve(OUT_DIR, 'zcta_population.js'),
`// Auto-generated. Total population per ZCTA, ACS 2022 5-year B01003.
export const ZCTA_POPULATION = ${JSON.stringify(pop)};
`);
  console.log('wrote ZCTA income + population data files');
}

main().catch(err => { console.error(err); process.exit(1); });
